/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asile_easychess_tb_RtbProbe */

#ifndef _Included_com_asile_easychess_tb_RtbProbe
#define _Included_com_asile_easychess_tb_RtbProbe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asile_easychess_tb_RtbProbe
 * Method:    probe
 * Signature: ([BZIIII[I)V
 */
JNIEXPORT void JNICALL Java_com_asile_easychess_tb_RtbProbe_probe
  (JNIEnv *, jobject, jbyteArray, jboolean, jint, jint, jint, jint, jintArray);

/*
 * Class:     com_asile_easychess_tb_RtbProbe
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_asile_easychess_tb_RtbProbe_init
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
