/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asile_easychess_gtb_GtbProbe */

#ifndef _Included_com_asile_easychess_tb_GtbProbe
#define _Included_com_asile_easychess_tb_GtbProbe
#ifdef __cplusplus
extern "C" {
#endif
#undef com_asile_easychess_tb_GtbProbe_NOPIECE
#define com_asile_easychess_tb_GtbProbe_NOPIECE 0L
#undef com_asile_easychess_tb_GtbProbe_PAWN
#define com_asile_easychess_tb_GtbProbe_PAWN 1L
#undef com_asile_easychess_tb_GtbProbe_KNIGHT
#define com_asile_easychess_tb_GtbProbe_KNIGHT 2L
#undef com_asile_easychess_tb_GtbProbe_BISHOP
#define com_asile_easychess_tb_GtbProbe_BISHOP 3L
#undef com_asile_easychess_tb_GtbProbe_ROOK
#define com_asile_easychess_tb_GtbProbe_ROOK 4L
#undef com_asile_easychess_tb_GtbProbe_QUEEN
#define com_asile_easychess_tb_GtbProbe_QUEEN 5L
#undef com_asile_easychess_tb_GtbProbe_KING
#define com_asile_easychess_tb_GtbProbe_KING 6L
#undef com_asile_easychess_tb_GtbProbe_NOSQUARE
#define com_asile_easychess_tb_GtbProbe_NOSQUARE 64L
#undef com_asile_easychess_tb_GtbProbe_H1_CASTLE
#define com_asile_easychess_tb_GtbProbe_H1_CASTLE 8L
#undef com_asile_easychess_tb_GtbProbe_A1_CASTLE
#define com_asile_easychess_tb_GtbProbe_A1_CASTLE 4L
#undef com_asile_easychess_tb_GtbProbe_H8_CASTLE
#define com_asile_easychess_tb_GtbProbe_H8_CASTLE 2L
#undef com_asile_easychess_tb_GtbProbe_A8_CASTLE
#define com_asile_easychess_tb_GtbProbe_A8_CASTLE 1L
#undef com_asile_easychess_tb_GtbProbe_DRAW
#define com_asile_easychess_tb_GtbProbe_DRAW 0L
#undef com_asile_easychess_tb_GtbProbe_WMATE
#define com_asile_easychess_tb_GtbProbe_WMATE 1L
#undef com_asile_easychess_tb_GtbProbe_BMATE
#define com_asile_easychess_tb_GtbProbe_BMATE 2L
#undef com_asile_easychess_tb_GtbProbe_FORBID
#define com_asile_easychess_tb_GtbProbe_FORBID 3L
#undef com_asile_easychess_tb_GtbProbe_UNKNOWN
#define com_asile_easychess_tb_GtbProbe_UNKNOWN 7L
/*
 * Class:     com_asile_easychess_tb_GtbProbe
 * Method:    probeHard
 * Signature: (ZII[I[I[B[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_asile_easychess_tb_GtbProbe_probeHard
  (JNIEnv *, jobject, jboolean, jint, jint, jintArray, jintArray, jbyteArray, jbyteArray, jintArray);

/*
 * Class:     com_asile_easychess_tb_GtbProbe
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_asile_easychess_tb_GtbProbe_init
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
